# -*- coding: utf-8 -*-
"""PalmerPenguinsM5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icSoSRVyd4iBtCt2AWYGOArMM44Uea9w
"""

# PalmerPenguinsM5.py
# Walter Lorimin
# 10/3/2026
# Uses loops to repeatedly explore palmer penguin statistics.

import math
# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

#The palmer penguins dataset contains observations for 342 penguins
#constant
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

#List of species names
species_names = [
 SP_CHINSTRAP,
 SP_GENTOO,
 SP_ADELIE]

 #Species count list
species_count = [
  NUM_CHINSTRAP,
  NUM_GENTOO,
  NUM_ADELIE
  ]

total_species = len(species_names)

#Calculation of the total number of penguins using sum()

total_penguins = sum(species_count)

#Average Number of Penguins per species
average_penguins = total_penguins / total_species

#percentage of each species
chinstrap_percent = species_count[0] / total_penguins * 100
gentoo_percent = species_count[1] / total_penguins * 100
adelie_percent = species_count[2] / total_penguins * 100

#Species percentage list
species_percentages = [
    chinstrap_percent,
    gentoo_percent,
    adelie_percent
]

#Species with most and fewest observations using max()and min()
largest_count = max(species_count)
smallest_count = min(species_count)
largest_index = species_count.index(largest_count)
smallest_index = species_count.index(smallest_count)
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

#use math Module
average_penguins_rounded_up = math.ceil(average_penguins)

# output the species names with introductory text
print("Introducing the Palmer Penguins:")
print()
print(f"\t{SP_CHINSTRAP}!")
print(f"\t{SP_GENTOO}!")
print("and last but not least...")
print(f"\t{SP_ADELIE}!")
print()
print(f"There are a total of {total_species} penguin species in this dataset.")
print(f"There are a total of {total_penguins} penguins in the dataset.")
print("The average number of penguins per species is "
      f"{average_penguins:.1f}")
print(f"The average rounded up is {average_penguins_rounded_up} penguins.")
print()

#species statistics useing a for loop
for index, species in enumerate(species_names):
    count = species_count[index]
    percentage = species_percentages[index]
    print(f"{species}: {count} ({percentage:.2f}%)")

print()
print("The species with the most observations is ",end="")
print(f"{largest_species} with {largest_count} penguins.")
print("The species with the fewest observations is ",end="")
print(f"{smallest_species} with {smallest_count} penguins.")
print()
#Counter for valid species selections
valid_selections = 0
#Interactive species selection
print("Explore a species:")
print()
species_choice = input("Enter Chinstrap, Gentoo, Adelie, or Done: ")
print()
while species_choice != "Done":
    if species_choice not in species_names:
        print(f"{species_choice} is not one of the species in this dataset.")
    else:
        if  species_choice == species_names[0]:
            selected_index = 0
        elif species_choice == species_names[1]:
            selected_index = 1
        else:
            selected_index = 2
        valid_selections += 1

        #Retrieving the selected species data
        selected_species = species_names[selected_index]
        selected_count = species_count[selected_index]
        selected_percent = species_percentages[selected_index]

        #classification of the species by percentage
        if selected_percent < 25:
            size_category = "small"
        elif (selected_percent >= 25) and (selected_percent <40):
            size_category = "medium"
        else:
            size_category = "large"

        #Species' relative position
        if (selected_species == largest_species)or\
            (selected_species == smallest_species):
            if selected_species == largest_species:
                position_description = "largest"
            else:
                position_description = "smallest"
        else:
            position_description = "middle-sized"

        #comparing the selected count to th avrage
        average_position = "above" if selected_count > average_penguins else "below"
        print()

        #Statistics for the selected species
        print(f"{selected_species} has {selected_count} observations, representing "
        f"{selected_percent:.2f}% of the dataset.")
        print(f"{selected_species} is classified as a {size_category} species group.")
        print(f"{selected_species} is the {position_description} species group.")
        print(f"Its observation count is {average_position} the dataset average of "
        f"{average_penguins:.1f}.")
    print()
    species_choice = input("Enter Chinstrap, Gentoo, Adelie, or Done: ")
    print()
print(f"You explored {valid_selections} valid species.\n"
      "Exploration complete.")